### ISSUE TITLE
Need to sync to AUR

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-tf2-py#2]

**Comment by jwhendy** [comment]
Seconded. I'm running into python3.8 issues which require rebuilding, but when I rebuild, I undo all of my local package builds since it's pulling from AUR.

@bionade24 how can we help you with the CI or whatever scripts you're using? I would love if packages synced overnight as soon as we update here. Do you have any objections to that?

**Comment by bionade24** [comment]
Sorry, freecad build broke at 98% all of time, so it stole lots of hours. Should be built in and pushed in some hours, only `ros-melodic-tf2` is still missing as dependency. The problem is simply that I can only use 2 Cores for building on my server, otherwise I would slow down all my other things. And I also now that this is annoying, but in the beginning I had many dependency issues in AUR comments and we still have some issues that only appear in clean chroots, so this is also important for getting the packages in @acxz 's proposal arch4edu. I still will simply push without checking that it builds, if you notice me like this.

**Comment by acxz** [comment]
@bionade24 is it at least possible to have a publicly available constantly updating log/build output file from your CI, so we can at least follow the errors that show up. This will also help us resolve the sync to AUR issues, along with us helping with dependency checking.

**Comment by jwhendy** [comment]
> still have some issues that only appear in clean chroots

That's a good point, and I have indeed expected that if one of us builds locally, that's good enough to push here. I do agree that building cleanly is a good best practice and forgot you were doing that.

> This will also help us resolve the sync to AUR issues, along with us helping with dependency checking.

Agreed with this. We can only do so much through github, it appears. That said, I can imagine this would be a potential pain since it's your server (logins, permissions, etc.). Maybe we should reinvestigate a legit build farm like we talked about initially?

**Comment by bionade24** [comment]
@acxz Wanted to get the packages into arch4edu. He also already spoke with the maintainer. The real problem about the way yet is that I can't use `[unstable]` without having more dependencies at new versions than just the wanted package. So if there is neither a python nor boost change, it won't take long until it's synced.

**Comment by bionade24** [comment]
> @bionade24 is it at least possible to have a publicly available constantly updating log/build output file from your CI, so we can at least follow the errors that show up. This will also help us resolve the sync to AUR issues, along with us helping with dependency checking.

Sorry, I simply wrote some python stuff because no CI really fitted the needs. I currently only see that one package failed and suppress the output in the cronjob. Maybe a webinterface would be an idea for the future, but I think the best idea is to simply wait a bit after new python/boost release, since even community and extra packages haven't worked afterwards.

**Comment by bionade24** [comment]
[This](https://github.com/bionade24/aur-ci) the most of the scripting currently. If this really needs to be a permanent solution, I'll make some web interface where you can get the logs. One task I also haven't done yet is to execute them in dependency order, but I think I can use `pyalpm` there. The real problem is that the only server with enough power I own runs debian, so I had to make many workarounds, like using & patching `docker-makepkg` (its code was a mess).
